### ISSUE TITLE
Не работает в IE 11

### ISSUE THREAD

**Issue by andreysolovyov** [mpMelnikov/WannaBeFullStack#1]
Тесты не проходят в IE 11. 
Результат выполнения:

ReferenceError: "EratosthenesSieve" не определено
   at Anonymous function (file:///C:/Users/somepath/WannaBeFullStack-master/1_eratosthenes/tests.js:11:9)
   at callFn (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4496:5)
   at Runnable.prototype.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4489:7)
   at Runner.prototype.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4892:5)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4970:7)
   at next (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4817:7)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4827:7)
   at next (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4766:16)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:4794:5)
   at timeslice (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.js:6218:5)

**Comment by mpMelnikov** [comment]
@andreysolovyov есть идеи, в чем может быть разница с Crome 72.0, где всё работает?

**Comment by andreysolovyov** [comment]
@mpMelnikov потому, что ты используешь стрелочные функции, которые не поддерживаются в IE11.

**Comment by mpMelnikov** [comment]
@andreysolovyov йиииии

**Comment by andreysolovyov** [comment]
Открыл PR. #3
